/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liquiD
 */
public class PorPrecioGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form PorPrecioGUI
     */
    public PorPrecioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maxPriceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        precioTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        minPriceField = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Búsqueda por precio");

        jLabel1.setText("Rango de precio:");

        maxPriceField.setText("Max");
        maxPriceField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxPriceFieldMouseClicked(evt);
            }
        });

        precioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(precioTable);

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        minPriceField.setText("Min");
        minPriceField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minPriceFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(minPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(maxPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        DefaultTableModel precioTableModel = (DefaultTableModel) precioTable.getModel();

        clearTable();

        try {
            float minNum = Float.parseFloat(minPriceField.getText());
            float maxNum = Float.parseFloat(maxPriceField.getText());

            for (Producto producto : MenuGUI.listaProductos) {
                if (producto.getPrecio() > minNum && producto.getPrecio() < maxNum) {
                    precioTableModel.addRow(new Object[]{
                        producto.getCodigo(), producto.getDescripcion(),
                        "$ " + producto.getPrecio(), producto.getStock()});
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor ingresado es incorrecto",
                    "ERROR", JOptionPane.WARNING_MESSAGE);
            minPriceField.setText("Min");
            maxPriceField.setText("Max");
        }


    }//GEN-LAST:event_searchButtonActionPerformed

    private void minPriceFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minPriceFieldMouseClicked
        if (minPriceField.getText().isEmpty() || minPriceField.getText().equals("Min")) {
            minPriceField.setText("");
        }
    }//GEN-LAST:event_minPriceFieldMouseClicked

    private void maxPriceFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxPriceFieldMouseClicked
        if (maxPriceField.getText().isEmpty() || maxPriceField.getText().equals("Max")) {
            maxPriceField.setText("");
        }
    }//GEN-LAST:event_maxPriceFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maxPriceField;
    private javax.swing.JTextField minPriceField;
    private javax.swing.JTable precioTable;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

    private void clearTable() {

        DefaultTableModel precioTableModel = (DefaultTableModel) precioTable.getModel();

        int filas = precioTable.getRowCount() - 1;

        for (int i = filas; i >= 0; i--) {
            precioTableModel.removeRow(i);
        }

    }

}
