/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado.ventanas;

import javax.swing.table.DefaultTableModel;
import supermercado.MenuGUI;
import supermercado.Producto;

/**
 *
 * @author liquiD
 */
public class PorNombreGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form porNombreGUI
     */
    public PorNombreGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        nTabla = new javax.swing.JTable();

        setClosable(true);
        setTitle("Búsqueda por nombre");

        jLabel1.setText("Producto a buscar:");

        nField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nFieldKeyReleased(evt);
            }
        });

        nTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(nTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nFieldKeyReleased

        DefaultTableModel nTablaModel = (DefaultTableModel) nTabla.getModel();

        clearTable();

        for (Producto producto : MenuGUI.listaProductos) {

            String search = nField.getText().toLowerCase(); //variable creada para comparación insensible a Mayus/Min

            if (producto.getDescripcion().toLowerCase().startsWith(search)) {
                nTablaModel.addRow(new Object[]{producto.getCodigo(),
                    producto.getDescripcion(), "$ " + producto.getPrecio(),
                    producto.getStock()
                });
            }
        }

    }//GEN-LAST:event_nFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nField;
    private javax.swing.JTable nTabla;
    // End of variables declaration//GEN-END:variables

    private void clearTable() {

        DefaultTableModel nTablaModel = (DefaultTableModel) nTabla.getModel();

        int filas = nTabla.getRowCount() - 1;

        for (int i = filas; i >= 0; i--) {
            nTablaModel.removeRow(i);
        }

    }

}
